CREATE TYPE "currency" AS ENUM (
  'stg £',
  'euro €',
  'dollar $',
  'yen'
);

CREATE TABLE "accounts" (
  "acc_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "acc_code" varchar UNIQUE NOT NULL,
  "acc_desc" varchar NOT NULL DEFAULT 'unused',
  "acc_type" varchar NOT NULL DEFAULT 'unused',
  "acc_pos" integer NOT NULL DEFAULT 85,
  "acc_source" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "contacts" (
  "con_id" integer PRIMARY KEY,
  "con_name" varchar,
  "con_member" boolean,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "transactions" (
  "tra_id" integer PRIMARY KEY,
  "tra_per_id" integer,
  "tra_date" Date,
  "tra_reference" varchar,
  "tra_contact" varchar,
  "tra_from_to" varchar,
  "tra_detail" varchar,
  "tra_source_id" integer,
  "tra_analysis_id" integer,
  "tra_gross" decimal,
  "tra_vat" decimal,
  "tra_net" decimal,
  "tra_tick" boolean,
  "tra_group" varchar,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "results" (
  "res_id" integer PRIMARY KEY,
  "res_per_code" varchar,
  "res_acc_code" varchar,
  "res_currency" varchar,
  "res_amount" decimal,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "currencies" (
  "cur_id" integer PRIMARY KEY,
  "cur_code" varchar,
  "cur_desc" varchar,
  "cur_symbol" currency,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "periods" (
  "per_id" integer PRIMARY KEY,
  "per_code" varchar UNIQUE NOT NULL,
  "per_desc" varchar UNIQUE NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE INDEX ON "transactions" ("tra_contact");

CREATE INDEX ON "transactions" ("tra_source_id");

CREATE INDEX ON "transactions" ("tra_analysis_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("tra_per_id") REFERENCES "periods" ("per_id");

ALTER TABLE "results" ADD FOREIGN KEY ("res_per_code") REFERENCES "periods" ("per_code");

ALTER TABLE "results" ADD FOREIGN KEY ("res_acc_code") REFERENCES "accounts" ("acc_code");

ALTER TABLE "transactions" ADD FOREIGN KEY ("tra_source_id") REFERENCES "accounts" ("acc_id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("tra_analysis_id") REFERENCES "accounts" ("acc_id");
