// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	AccID     int32
	AccCode   string
	AccDesc   string
	AccType   string
	AccPos    int32
	AccSource bool
	CreatedAt time.Time
}

type Contact struct {
	ConID     int32
	ConName   sql.NullString
	ConMember sql.NullBool
	CreatedAt sql.NullTime
}

type Currency struct {
	CurID     int32
	CurCode   sql.NullString
	CurDesc   sql.NullString
	CurSymbol sql.NullString
	CreatedAt sql.NullTime
}

type Period struct {
	PerID     int32
	PerDesc   string
	CreatedAt sql.NullTime
}

type Result struct {
	ResID       int32
	ResPerID    sql.NullString
	ResAccID    sql.NullString
	ResCurrency sql.NullString
	ResAmount   sql.NullString
	CreatedAt   sql.NullTime
}

type Transaction struct {
	TraID         int32
	TraPerID      sql.NullInt32
	TraDate       sql.NullTime
	TraReference  sql.NullString
	TraContact    sql.NullString
	TraFromTo     sql.NullString
	TraDetail     sql.NullString
	TraSourceID   sql.NullInt32
	TraAnalysisID sql.NullInt32
	TraGross      sql.NullString
	TraVat        sql.NullString
	TraNet        sql.NullString
	TraTick       sql.NullBool
	TraGroup      sql.NullString
	CreatedAt     sql.NullTime
}
